### ISSUE TITLE
Can't Read Files

### ISSUE THREAD

**Issue by M-GRV** [Attacler/directus-extension-admin-panels#1]
Hey! 

Just installed and for my instance M2M is working fine, but looking for files it runs into an error.

![image](https://github.com/Attacler/directus-extension-admin-panels/assets/130182174/b1e7d2c2-1628-4d92-a8f7-343ee2f0f5c5)

Thanks!

**Comment by Attacler** [comment]
Hi @M-GRV,

Thank you for reporting this bug.
Before i can do anything, i will need some more intel.
Do you see any error logs inside of Directus itself?
If you open dev tools -> network and reopen the insight, what response are you getting on the files endpoint?

**Comment by M-GRV** [comment]
> Hi @M-GRV,
> 
> Thank you for reporting this bug. Before i can do anything, i will need some more intel. Do you see any error logs inside of Directus itself? If you open dev tools -> network and reopen the insight, what response are you getting on the files endpoint?

I will take a look and let you know!

**Comment by Attacler** [comment]
Closed this issue due to inactivity.

**Comment by M-GRV** [comment]
> Hi @M-GRV,
> 
> Thank you for reporting this bug. Before i can do anything, i will need some more intel. Do you see any error logs inside of Directus itself? If you open dev tools -> network and reopen the insight, what response are you getting on the files endpoint?

There was no error within network.  Only in console

![image](https://github.com/Attacler/directus-extension-admin-panels/assets/130182174/73462fd1-d7ee-4cde-8314-9cc0a20da12b)
@Attacler 

Everything in network is 200

**Comment by Attacler** [comment]
Thanks @M-GRV for reporting this issue, i just pushed an update to fix this issue.
Feel free to open a new issue if anything else breaks.
